#!/usr/bin/env bash

# This wraps the menumaker logic and renders menus graphically with rofi
# $1 - Menu content (a string with newlines)
# $2 - Prompt text (a string)
# $3 - Auto-selection option (a boolean)
function RENDERMENU() {
    if [[ $# -ne 3 ]]; then
		>&2 echo "ERROR: RENDERMENU requires 3 arguments (got $#)"
		>&2 echo "    - The menu content (value: \"$1\")"
		>&2 echo "    - The prompt text (value: \"$2\")"
		>&2 echo "    - Boolean for autoselect (value: \"$3\")"
		exit -1
    fi
    if [[ "$(uname)" == "linux-gnu" ]]; then
	if [[ "$3" == true ]]; then
	    echo -e "$1" | rofi -dmenu -p "$2"
	else
	    echo -e "$1" | rofi -dmenu -p "$2"
	fi
    fi
    if [[ "$(uname)" == "darwin" ]]; then
	if [[ "$3" == true ]]; then
	    echo -e "$1" | xmenu -H 20 -p "$2"
	else
	    echo -e "$1" | xmenu -H 20 -p "$2"
	fi
    fi
}

source menugenbase
